// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjc2Y2bKm7VxvRM-nKBeLSPyKJBFPSqhg',
    appId: '1:809514308288:web:c07d00f1a48110fd509325',
    messagingSenderId: '809514308288',
    projectId: 'escritorio-jm-c8ffd',
    authDomain: 'escritorio-jm-c8ffd.firebaseapp.com',
    storageBucket: 'escritorio-jm-c8ffd.appspot.com',
    measurementId: 'G-R5LRQ10S51',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjc2Y2bKm7VxvRM-nKBeLSPyKJBFPSqhg',
    appId: '1:809514308288:web:e2eac0c9fcaf7455509325',
    messagingSenderId: '809514308288',
    projectId: 'escritorio-jm-c8ffd',
    authDomain: 'escritorio-jm-c8ffd.firebaseapp.com',
    storageBucket: 'escritorio-jm-c8ffd.appspot.com',
    measurementId: 'G-ZJ5BF0FYWH',
  );

}